#!/bin/bash

# Luna Session End Hook
# Cleans up Luna session, saves final state, and generates summary

PLUGIN_ROOT="${CLAUDE_PLUGIN_ROOT}"
SESSION_LOG="${PLUGIN_ROOT}/logs/session.log"
WORKSPACE_ROOT="${PLUGIN_ROOT}/workspace"
LUNA_STATE="${WORKSPACE_ROOT}/.luna-state.json"

echo "[$(date '+%Y-%m-%d %H:%M:%S')] 🌙 Luna Agents Session Ending..." >> "$SESSION_LOG"

# Update session state with end time
if [[ -f "$LUNA_STATE" ]]; then
    jq '.session_end = "'$(date -Iseconds)'" "$LUNA_STATE" > "${LUNA_STATE}.tmp" && mv "${LUNA_STATE}.tmp" "$LUNA_STATE"
fi

# Generate session summary
COMMAND_COUNT=$(cat "$PLUGIN_ROOT/logs/human-readable.log" 2>/dev/null | wc -l || echo "0")
ERROR_COUNT=$(grep -c "ERROR\|Failed" "$SESSION_LOG" 2>/dev/null || echo "0")

cat > "$WORKSPACE_ROOT/session-summary.json" << EOF
{
  "session_end": "$(date -Iseconds)",
  "total_commands": $COMMAND_COUNT,
  "errors_encountered": $ERROR_COUNT,
  "workspace_directory": "$(pwd)",
  "files_modified": $(wc -l < "$WORKSPACE_ROOT/changes.log" 2>/dev/null || echo "0"),
  "last_activity": "$(tail -1 "$PLUGIN_ROOT/logs/human-readable.log" 2>/dev/null | cut -d']' -f2 || 'No activity')"
}
EOF

# Log session summary
echo "[$(date '+%Y-%m-%d %H:%M:%S')] 📊 Session Summary:" >> "$SESSION_LOG"
echo "  - Total Commands: $COMMAND_COUNT" >> "$SESSION_LOG"
echo "  - Errors: $ERROR_COUNT" >> "$SESSION_LOG"
echo "  - Files Modified: $(wc -l < "$WORKSPACE_ROOT/changes.log" 2>/dev/null || echo "0")" >> "$SESSION_LOG"

# Clean up temporary files
find "$PLUGIN_ROOT" -name "*.tmp" -delete 2>/dev/null || true

echo "[$(date '+%Y-%m-%d %H:%M:%S')] ✅ Luna Agents session ended successfully" >> "$SESSION_LOG"

# Create session report
REPORT_FILE="$WORKSPACE_ROOT/session-report-$(date +%Y%m%d-%H%M%S).md"
cat > "$REPORT_FILE" << EOF
# Luna Session Report

**Session Date:** $(date '+%Y-%m-%d %H:%M:%M')
**Workspace:** $(pwd)

## Statistics
- **Total Commands:** $COMMAND_COUNT
- **Errors Encountered:** $ERROR_COUNT
- **Files Modified:** $(wc -l < "$WORKSPACE_ROOT/changes.log" 2>/dev/null || echo "0")

## Recent Activity
$(tail -5 "$PLUGIN_ROOT/logs/human-readable.log" 2>/dev/null || echo "No activity recorded")

## Workspace State
Current Luna workspace state saved in: \`$LUNA_STATE\`

## Next Steps
1. Review implementation plan progress
2. Check any issues found during the session
3. Continue with next Luna workflow phase

---
*Generated by Luna Agents - $(date)*
EOF

exit 0