#!/bin/bash

# Luna Session Report Hook
# Generates session completion report with statistics

PLUGIN_ROOT="${CLAUDE_PLUGIN_ROOT}"
SESSION_LOG="${PLUGIN_ROOT}/logs/session.log"
REPORTS_DIR="${PLUGIN_ROOT}/reports"

mkdir -p "$REPORTS_DIR" "$(dirname "$SESSION_LOG")"

TIMESTAMP=$(date +%Y%m%d-%H%M%S)
REPORT_FILE="$REPORTS_DIR/session-report-$TIMESTAMP.md"

echo "[$(date '+%Y-%m-%d %H:%M:%S')] 📊 Generating session report..." >> "$SESSION_LOG"

# Get session statistics
COMMAND_COUNT=$(jq -r '.total_commands // 0' "$PLUGIN_ROOT/data/command-count.json" 2>/dev/null || echo "0")
ERROR_COUNT=$(jq -r '.total_errors // 0' "$PLUGIN_ROOT/data/error-recovery.json" 2>/dev/null || echo "0")
NOTIFICATION_COUNT=$(jq -r '.total_notifications // 0' "$PLUGIN_ROOT/data/notification-analytics.json" 2>/dev/null || echo "0")

# Generate report
cat > "$REPORT_FILE" << EOF
# Luna Session Report

**Generated:** $(date '+%Y-%m-%d %H:%M:%S')
**Workspace:** $(pwd)

## Session Statistics
- **Commands Executed:** $COMMAND_COUNT
- **Errors Encountered:** $ERROR_COUNT
- **Notifications Received:** $NOTIFICATION_COUNT

## Recent Activity
$(tail -10 "$PLUGIN_ROOT/logs/human-readable.log" 2>/dev/null | sed 's/^/ - /' || echo "No recent activity")

## Files Modified
$(find . -name "*.md" -o -name "*.js" -o -name "*.ts" -o -name "*.py" -o -name "*.go" | head -10 | sed 's/^/ - /' || echo "No modified files found")

## Next Steps
1. Review completed tasks
2. Check for any errors that need attention
3. Plan next Luna workflow phase

---
*Generated by Luna Agents v1.0.0*
EOF

echo "[$(date '+%Y-%m-%d %H:%M:%S')] ✅ Session report generated: $REPORT_FILE" >> "$SESSION_LOG"

# Clean old reports (keep last 5)
find "$REPORTS_DIR" -name "session-report-*.md" | sort -r | tail -n +6 | xargs rm -f 2>/dev/null || true

exit 0