#!/usr/bin/env node
// Sync README.md counters + auto-generated sections against actual repo contents.
// Usage:
//   node scripts/sync-readme.mjs            # write
//   node scripts/sync-readme.mjs --check    # exit 1 if drift (for CI)

import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";

const __filename = fileURLToPath(import.meta.url);
const root = resolve(dirname(__filename), "..");
const README = join(root, "README.md");
const COMMANDS_DIR = join(root, "commands");
const AGENTS_DIR = join(root, "agents");
const SKILLS_DIR = join(root, "skills");

const args = new Set(process.argv.slice(2));
const checkOnly = args.has("--check");

function listMd(dir) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith(".md"))
    .filter((f) => f.toLowerCase() !== "readme.md")
    .sort();
}

function readFront(file) {
  try {
    const txt = readFileSync(file, "utf8");
    const m = txt.match(/^---\n([\s\S]*?)\n---/);
    if (!m) return {};
    const out = {};
    for (const line of m[1].split("\n")) {
      const i = line.indexOf(":");
      if (i === -1) continue;
      const k = line.slice(0, i).trim();
      const v = line.slice(i + 1).trim().replace(/^["']|["']$/g, "");
      out[k] = v;
    }
    return out;
  } catch {
    return {};
  }
}

function firstSentence(file) {
  try {
    const txt = readFileSync(file, "utf8").replace(/^---[\s\S]*?---\n?/, "");
    const para = txt.split(/\n\n+/).find((p) => p.trim() && !p.startsWith("#")) ?? "";
    const s = para.replace(/\s+/g, " ").trim();
    return s.length > 140 ? s.slice(0, 137) + "..." : s;
  } catch {
    return "";
  }
}

function fence(content) {
  return "```\n" + content + "\n```";
}

function section(marker, body) {
  return `<!-- LUNA:${marker}-START -->\n${body}\n<!-- LUNA:${marker}-END -->`;
}

function replaceMarked(src, marker, body) {
  const re = new RegExp(
    `<!-- LUNA:${marker}-START -->[\\s\\S]*?<!-- LUNA:${marker}-END -->`,
    "m"
  );
  const block = section(marker, body);
  if (re.test(src)) return src.replace(re, block);
  return src + "\n\n" + block + "\n";
}

const commands = listMd(COMMANDS_DIR);
const agents = listMd(AGENTS_DIR);
const skills = listMd(SKILLS_DIR);
const cmdCount = commands.length;
const agentCount = agents.length;
const skillCount = skills.length;

function buildCommandIndex() {
  const lines = [`> Auto-generated by \`npm run readme:sync\`. Do not edit by hand.`, ""];
  lines.push("| Command | Description |");
  lines.push("|:--------|:------------|");
  for (const f of commands) {
    const path = join(COMMANDS_DIR, f);
    const fm = readFront(path);
    const name = f.replace(/\.md$/, "");
    const desc = (fm.description || firstSentence(path) || "").replace(/\|/g, "\\|");
    lines.push(`| \`/luna-agents:${name}\` | ${desc} |`);
  }
  return lines.join("\n");
}

function buildAgentList() {
  const lines = ["| Agent | Description |", "|:------|:------------|"];
  for (const f of agents) {
    const path = join(AGENTS_DIR, f);
    const fm = readFront(path);
    const name = f.replace(/\.md$/, "").replace(/^luna-/, "");
    const desc = (fm.description || firstSentence(path) || "").replace(/\|/g, "\\|");
    lines.push(`| \`${name}\` | ${desc} |`);
  }
  return lines.join("\n");
}

function buildCounters() {
  return [
    "<!-- counters: command/agent/skill totals are updated by sync-readme.mjs -->",
    `- **Commands:** ${cmdCount}`,
    `- **Agents:** ${agentCount}`,
    `- **Skills:** ${skillCount}`,
  ].join("\n");
}

let readme = readFileSync(README, "utf8");
const before = readme;

readme = readme.replace(/\b\d+\s+specialized AI agents\b/g, `${agentCount} specialized AI agents`);
readme = readme.replace(/\b\d+\s+slash commands\b/g, `${cmdCount} slash commands`);
readme = readme.replace(/\*\*\d+\s+slash commands\*\*/g, `**${cmdCount} slash commands**`);
readme = readme.replace(/Claude Code Commands\s*\(\d+\)/g, `Claude Code Commands (${cmdCount})`);
readme = readme.replace(/Type `\/cmds` to see all\d* commands?\./g, `Type \`/cmds\` to see all ${cmdCount} commands.`);
readme = readme.replace(/includes\s+\d+\s+slash commands/g, `includes ${cmdCount} slash commands`);
readme = readme.replace(/all\s+\d+\s+commands/gi, `all ${cmdCount} commands`);

readme = replaceMarked(readme, "COUNTERS", buildCounters());
readme = replaceMarked(readme, "COMMAND-INDEX", buildCommandIndex());
readme = replaceMarked(readme, "AGENT-LIST", buildAgentList());

if (checkOnly) {
  if (before !== readme) {
    console.error("README.md is out of sync with commands/ + agents/. Run: npm run readme:sync");
    process.exit(1);
  }
  console.log(`README.md in sync (${cmdCount} commands, ${agentCount} agents, ${skillCount} skills).`);
  process.exit(0);
}

if (before === readme) {
  console.log(`README.md already in sync (${cmdCount} commands, ${agentCount} agents, ${skillCount} skills).`);
  process.exit(0);
}

writeFileSync(README, readme);
console.log(`README.md synced. Now: ${cmdCount} commands, ${agentCount} agents, ${skillCount} skills.`);
